# Global configuration
horizon: 14
test_days: 28  # last N days for validation/test split

# Modeling
model_type: xgboost  # options: xgboost, sarimax
xgb:
  max_depth: 6
  n_estimators: 400
  learning_rate: 0.06
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1.0

sarimax:
  order: [1,1,1]
  seasonal_order: [1,1,1,7]

# Inventory economics
economics:
  unit_cost: 10.0
  unit_price: 15.0
  holding_cost: 0.5
  stockout_cost: 5.0
